{{- if .Values.clusterAutoscaler.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-cluster-autoscaler
  namespace: {{ .Values.argoNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    targetRevision: {{ .Values.clusterAutoscaler.targetRevision | quote }}
    helm:
      releaseName: cluster-autoscaler
      version: v3
      {{- with .Values.clusterAutoscaler.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-autoscaler
  syncPolicy:
  {{- toYaml .Values.clusterAutoscaler.syncPolicy | nindent 4 }}
{{- end }}
