{{- if .Values.grafana.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Values.argoNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: {{ .Values.grafana.targetRevision | quote }}
    helm:
      releaseName: grafana
      version: v3
      {{- with .Values.grafana.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
  {{- toYaml .Values.grafana.syncPolicy | nindent 4 }}
{{- end }}
