{{ if .Values.linkerdCrds.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-linkerd-crds
  namespace: {{ .Values.argoNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-crds
    targetRevision: {{ .Values.linkerdCrds.targetRevision | quote }}
    helm:
      releaseName: linkerd-crds
      version: v3
      {{- with .Values.linkerdCrds.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
  {{- toYaml .Values.linkerdCrds.syncPolicy | nindent 4 }}
  {{- with .Values.linkerdCrds.ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
