{{- if and (.Values.certManager.enabled) (.Values.linkerd.enabled)}}
apiVersion: v1
kind: Secret
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
data:
  tls.crt: |
    {{- .Values.linkerd.values.identityTrustAnchorsPEM | b64enc | trim | nindent 4 }}
  tls.key: |
    {{- .Values.linkerd.trustAnchor.key | b64enc | trim | nindent 4 }}
type: kubernetes.io/tls
{{- end }}