{{- if and (.Values.loki.enabled) (.Values.loki.basicAuthSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.loki.basicAuthSecret.name }}
  namespace: loki
  labels:
{{ include "platform-services.labels" $ | indent 6 }}
type: Opaque
data:
  .htpasswd: {{ include "platform-services.lokihtpasswd" $ | b64enc | quote }}
{{- end}}
