{{- if .Values.storageClasses.aws.gp2.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.aws.gp2.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageClasses.aws.gp2.isDefaultStorageClass | quote }}
    resize.topolvm.io/enabled: "true"
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  fsType: ext4
---
{{- end }}
{{- if .Values.storageClasses.aws.encryptedGp2.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.aws.encryptedGp2.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageClasses.aws.encryptedGp2.isDefaultStorageClass | quote }}
    resize.topolvm.io/enabled: "true"
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
---
{{- end }}
{{- if .Values.storageClasses.aws.gp3.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.aws.gp3.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageClasses.aws.gp3.isDefaultStorageClass | quote }}
    resize.topolvm.io/enabled: "true"
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4
---
{{- end }}
{{- if .Values.storageClasses.aws.encryptedGp3.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.aws.encryptedGp3.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageClasses.aws.encryptedGp3.isDefaultStorageClass | quote }}
    resize.topolvm.io/enabled: "true"
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
---
{{- end }}
{{- if .Values.storageClasses.gke.ssd.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.gke.ssd.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageClasses.gke.ssd.isDefaultStorageClass | quote }}
    resize.topolvm.io/enabled: "true"
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-ssd
---
{{- end }}
{{- if .Values.storageClasses.gke.standard.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.gke.standard.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageClasses.gke.standard.isDefaultStorageClass | quote }}
    resize.topolvm.io/enabled: "true"
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-standard
---
{{- end }}
