{{- if .Values.velero.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-velero
  namespace: {{ .Values.argoNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: {{ .Values.velero.targetRevision | quote }}
    helm:
      releaseName: velero
      version: v3
      {{- with .Values.velero.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
  {{- toYaml .Values.velero.syncPolicy | nindent 4 }}
{{- end }}
