{{- if .Values.zalandoPostgresOperator.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-postgres-operator
  namespace: {{ .Values.argoNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    chart: postgres-operator
    targetRevision: {{ .Values.zalandoPostgresOperator.targetRevision | quote }}
    helm:
      releaseName: postgres-operator
      version: v3
      {{- with .Values.zalandoPostgresOperator.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-operator
  syncPolicy:
  {{- toYaml .Values.zalandoPostgresOperator.syncPolicy | nindent 4 }}
{{- end }}
