{
 "title": "Catalyst / gRPC Service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(grpc_server_handled_total{}, cluster)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(grpc_server_handled_total{cluster=\"$cluster\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Percentage of Successful Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{cluster=\"$cluster\",job=\"$service\",grpc_code=\"OK\"}[$__rate_interval]))\n/\nsum(rate(grpc_server_handled_total{cluster=\"$cluster\",job=\"$service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total Rate of Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{cluster=\"$cluster\",job=\"$service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Rate of Requests by GRPC Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (grpc_service) (rate(grpc_server_handled_total{cluster=\"$cluster\",job=\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{ grpc_service }}"
    }
   ]
  },
  {
   "title": "Rate of Requests by GRPC Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (grpc_method) (rate(grpc_server_handled_total{cluster=\"$cluster\",job=\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Request duration bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (grpc_server_handling_seconds_bucket{cluster=\"$cluster\",job=\"$service\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Duration 99th Quantile by GRPC Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$service\"}[$__rate_interval])) by (grpc_service,le)\n)",
     "legendFormat": "{{ grpc_service }}"
    }
   ]
  },
  {
   "title": "Request Duration 95th Quantile by GRPC Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$service\"}[$__rate_interval])) by (grpc_service,le)\n)",
     "legendFormat": "{{ grpc_service }}"
    }
   ]
  },
  {
   "title": "Rate of Failed Requests by GRPC Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (grpc_code) (rate(grpc_server_handled_total{cluster=\"$cluster\",job=\"$service\",grpc_code!=\"OK\"}[$__rate_interval]))",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  }
 ]
}