{
 "title": "Common / Loki",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Loki Resource Usage by Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Loki Ingester CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"cpu\",pod=~\"loki-distributed-ingester-.*\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-ingester-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Ingester Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"memory\",pod=~\"loki-distributed-ingester-.*\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-ingester-.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Distributor CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"cpu\",pod=~\"loki-distributed-distributor-.*\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-distributor-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Distributor Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"memory\",pod=~\"loki-distributed-distributor-.*\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-distributor-.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Gateway CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"cpu\",pod=~\"loki-distributed-gateway-.*\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-gateway-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Gateway Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"memory\",pod=~\"loki-distributed-gateway-.*\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-gateway-.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Querier CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"cpu\",pod=~\"loki-distributed-querier-.*\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-querier-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Querier Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"memory\",pod=~\"loki-distributed-querier-.*\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-querier-.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Query Frontend CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"cpu\",pod=~\"loki-distributed-query-frontend-.*\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-query-frontend-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Query Frontend Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"memory\",pod=~\"loki-distributed-query-frontend-.*\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-query-frontend-.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Index Gateway CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"cpu\",pod=~\"loki-distributed-index-gateway-.*\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-index-gateway-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Index Gateway Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"memory\",pod=~\"loki-distributed-index-gateway-.*\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-index-gateway-.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Compactor CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"cpu\",pod=~\"loki-distributed-compactor-.*\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-compactor-.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Compactor Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"loki\",resource=\"memory\",pod=~\"loki-distributed-compactor-.*\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"loki\",image!=\"\",container!=\"POD\",pod=~\"loki-distributed-compactor-.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Loki Persistent Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (\n  kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"data-loki-distributed.*\"} \n  / \n  kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"data-loki-distributed.*\"}\n) * 100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Promtail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Promtail - Rate of Sent Entries by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(promtail_sent_entries_total{}[$__rate_interval]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Promtail - Rate of Dropped Entries by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(promtail_dropped_entries_total{}[$__rate_interval]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}